### ISSUE TITLE
Message about "Ruler change Faith" keep repeating

### ISSUE THREAD

**Issue by DkHyacinth** [ThePinkPanzer/Godherja-Github-Version#134] opened 2022-03-30 15:32 UTC
One of my character's fellow vassal changed his faith to Omitilos Aagiokratia, and the information bar keep repeating this message.
I met this bug before but at that time the gameplay was nearly at the end so I didn't care about it, I cannot remember which faith that character change to now but probably not Omitilos Aagiokratia

**Comment by FedorBozic** [comment] 2022-04-01 21:10
Duplicate of
https://github.com/ThePinkPanzer/Godherja-Github-Version/issues/18

**Closed as completed by FedorBozic** 2022-04-01 21:10 UTC
Labels: duplicate
