### ISSUE TITLE
De jure territories of Kingdom of Lepolz are in a most suspicious place 

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#143] opened 2022-04-01 14:08 UTC
![Zrzut ekranu (158)](https://user-images.githubusercontent.com/101152217/161280171-73305ca2-2977-4aaf-add3-ed3f6d72a3e4.png)

**Comment by FatLeek** [comment] 2022-04-01 14:15
Cenware had to fight Benouet ; / And on screenshot Lepolz was held by partic, henceforth the name

**Comment by FedorBozic** [comment] 2022-04-01 21:13
Effectively a duplicate of:
https://github.com/ThePinkPanzer/Godherja-Github-Version/issues/138

**Closed as completed by FedorBozic** 2022-04-01 21:13 UTC
Labels: duplicate
