### ISSUE TITLE
Special Building "To Pedithipsi" wrong amount of Extended Magic Baseline

### ISSUE THREAD

**Issue by JamesIanM** [ThePinkPanzer/Godherja-Github-Version#560] opened 2023-10-30 19:44 UTC
In the "To Pedithipsi" building description it states that it gives +50 Extended Magic Baseline
However when Myrespiae is your capital you currently receive +1 Extended Magic Baseline from "To Pedithipsi"

**Comment by Bommelom1** [comment] 2023-11-07 18:03
Should be fixed for the next version - we had named the value responsible for giving the extended magic baseline "01_thesorrowfield_add = 50", but the problem is you apparently can't have values starting with numbers, as ""01_thesorrowfield_add" is just treated as 1.

**Closed as completed** 2023-11-07 18:03 UTC
Labels: bug, feature bug
