### ISSUE TITLE
Sarradon Reconquest 

### ISSUE THREAD

**Issue by Rawilson03** [ThePinkPanzer/Godherja-Github-Version#141] opened 2022-04-01 13:35 UTC
I let the Sarradon reconquest play out and noticed that the Agionist holy orders actually maintain their territories under Ibn Sarradon.

**Comment by UltimateVictory** [comment] 2022-04-25 00:03
Should be fixed for next patch, caused by hostility doctrine.

**Closed as completed by UltimateVictory** 2022-04-25 00:03 UTC
Labels: bug, feature bug
